import tapmoc.Severity

buildscript {
	dependencies {
		classpath libs.kotlin.gradlePlugin
		classpath libs.buildConfigPlugin
		classpath libs.gradleMavenPublishPlugin
		classpath libs.dokkaPlugin
		classpath libs.compatPlugin
		classpath 'com.jakewharton.cite:cite-gradle-plugin'
	}
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
}

allprojects {
	version = property("VERSION_NAME") as String

	repositories {
		mavenCentral()
		google()
		repositories {
			maven {
				url 'https://repo.gradle.org/gradle/libs-releases'
				metadataSources {
					mavenPom()
					ignoreGradleMetadataRedirection()
				}
				content {
					includeGroup('org.gradle.experimental')
				}
			}
		}
	}

	configurations.configureEach {
		resolutionStrategy.dependencySubstitution {
			substitute(module("com.jakewharton.cite:cite-kotlin-plugin"))
				.using(project(":cite-kotlin-plugin"))
				.because("In-repo sample usage")
		}
	}

	tasks.withType(Test).configureEach {
		testLogging {
			if (System.getenv("CI") == "true") {
				events = ["failed", "skipped", "passed"]
			}
			exceptionFormat "full"
		}
  }

	plugins.withId('com.gradleup.tapmoc') {
		tapmoc {
			checkDependencies(Severity.ERROR)
		}
  }

	plugins.withId('maven-publish') {
		publishing {
			repositories {
				maven {
					name = "TestMaven"
					url = file("${rootProject.buildDir}/testMaven").toURI().toString()
				}
			}
		}
	}
}
