buildscript {
	dependencies {
		classpath libs.kotlin.gradlePlugin
		classpath libs.buildConfigPlugin
	}
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
}

allprojects {
	version = '0-internal'

	repositories {
		mavenCentral()
		google()
	}

  tasks.withType(JavaCompile).configureEach { task ->
    task.sourceCompatibility = '11'
    task.targetCompatibility = '11'
  }

  tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile).configureEach { task ->
    task.kotlinOptions {
      jvmTarget = '11'
    }
  }
}
