buildscript {
	dependencies {
		classpath libs.kotlin.gradlePlugin
		classpath libs.buildConfigPlugin
		classpath libs.compatPlugin
	}
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
}

allprojects {
	version = '0-internal'

	repositories {
		mavenCentral()
		google()
		repositories {
			maven {
				url 'https://repo.gradle.org/gradle/libs-releases'
				metadataSources {
					mavenPom()
					ignoreGradleMetadataRedirection()
				}
				content {
					includeGroup('org.gradle.experimental')
				}
			}
		}
	}
}
