buildscript {
	dependencies {
		classpath libs.android.gradlePlugin
		classpath "com.jakewharton.cite:cite-gradle-plugin:$citeVersion"
	}
	repositories {
		mavenCentral()
		google()
		maven {
			url "file://${rootDir.absolutePath}/../../../../../build/testMaven"
		}
	}
}

apply plugin: 'com.jakewharton.cite'
apply plugin: 'com.android.test'

android {
	namespace = 'com.example.tests'
	compileSdk = 35

	defaultConfig {
		minSdk = 26
		targetProjectPath = ':app'
	}
}

dependencies {
	implementation libs.junit
}

allprojects {
	repositories {
		mavenCentral()
		google()
		maven {
			url "file://${rootDir.absolutePath}/../../../../../build/testMaven"
		}
	}
}
