[versions]
kotlin = "2.3.0-RC"

[libraries]
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

android-gradlePlugin = "com.android.tools.build:gradle:9.0.0-beta03"

kotlinCompilerTester = "dev.zacsweers.kctfork:core:0.11.1"

buildConfigPlugin = "com.github.gmazzo:gradle-buildconfig-plugin:3.1.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.35.0"
dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.1.0"

junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
asm-util = "org.ow2.asm:asm-util:9.9"
