[versions]
kotlin = "2.4.10"

[libraries]
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

android-gradlePlugin = "com.android.tools.build:gradle:9.3.0"

kotlinCompilerTester = "dev.zacsweers.kctfork:core:0.13.0"

buildConfigPlugin = "com.github.gmazzo.buildconfig:plugin:6.0.10"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.37.0"
dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.2.0"
compatPlugin = "com.gradleup.tapmoc:tapmoc-gradle-plugin:0.4.2"

junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector:1.22"
asm-util = "org.ow2.asm:asm-util:9.10.1"
