buildscript {
	dependencies {
		classpath libs.android.gradlePlugin
		classpath "com.jakewharton.cite:cite-gradle-plugin:$citeVersion"
	}
	repositories {
		mavenCentral()
		google()
		maven {
			url "file://${rootDir.absolutePath}/../../../../../build/testMaven"
		}
	}
}

apply plugin: 'com.jakewharton.cite'
apply plugin: 'com.android.library'

android {
	namespace = 'com.example'
	compileSdk = 35

	defaultConfig {
		minSdk = 26
	}
}

repositories {
	mavenCentral()
	google()
	maven {
		url "file://${rootDir.absolutePath}/../../../../../build/testMaven"
	}
}

dependencies {
	testImplementation libs.junit
}
